-- MySQL Script generated by MySQL Workbench
-- Wed Jan  5 17:03:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nota_fiscal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nota_fiscal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nota_fiscal` DEFAULT CHARACTER SET utf8 ;
USE `nota_fiscal` ;

-- -----------------------------------------------------
-- Table `nota_fiscal`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`nota_fiscal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_emissao` DATE NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nota_fiscal_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_nota_fiscal_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `nota_fiscal`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `descricao` VARCHAR(120) NOT NULL,
  `valor_unitario` DECIMAL(8,2) NOT NULL,
  `nota_fiscal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_nota_fiscal1_idx` (`nota_fiscal_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_nota_fiscal1`
    FOREIGN KEY (`nota_fiscal_id`)
    REFERENCES `nota_fiscal`.`nota_fiscal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `nota_fiscal`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bairro_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `nota_fiscal`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(4) NOT NULL,
  `complemento` VARCHAR(50) NOT NULL,
  `cliente_id` INT NOT NULL,
  `bairro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cliente_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_endereco_bairro1_idx` (`bairro_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `nota_fiscal`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `nota_fiscal`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_fiscal`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nota_fiscal`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefone_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `nota_fiscal`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
